const Langs = {
  en: {
    Login_page: {
      title: "Log in",
      username_placeholder: "Username",
      password_placeholder: "Password",
      trial_text: "This is a trial version",
      button_text: "Login",
      version_text: "POSoft version (1.0.0)",
    },

    Navigation: [
      "Cash",
      "Inverntory",
      "Transactions",
      "Clients",
      "Settings",
      "Info",
      "Exit",
    ],

    Cash: {
      products_list_columns: ["Name", "Quantity", "Price (DZD)"],
      product_search_placeholder: "Name/Barcode",
      digital_screen: {
        text_fields: [
          "Deal Number",
          "Product",
          "Price",
          "Barcode",
          "In Stock",
          "Total",
        ],
        moving_bottom_text: "Thank you for shopping with us",
      },
      controls: [
        "Qty +",
        "Qty -",
        "Cancel",
        "Manual",
        "Validate",
        "Credit",
        "Print ticket",
      ],
      add_manual: {
        name_placeholder: "Enter product",
        value_placeholder: "Enter Value (DZD)",
        button: "Add",
      },
      credit: {
        client_name_placeholder: "Enter client",
        button: "Add",
      },

      calculator: {
        input_placeholder: "Enter Amount (DZD)",
        button: "Calculate",
      },
    },

    Inventory: {
      search_placeholder: "Name / Barcode",
      nav_buttons: ["Add", "All", "Alerted", "Import", "Export PDF"],
      products_table_columns: [
        "Name",
        "Barcode",
        "Price (DZD)",
        "Buy Price (DZD)",
        "Stock",
        "Alert quantity",
        "Modify",
      ],
    },

    Transactions: {
      nav_fields: [
        "From",
        "Click to select",
        "To",
        "Filter by user",
        "TOTAL",
        "PROFIT",
      ],
      transactions_table_columns: [
        "Deal #",
        "Date",
        "Time",
        "Total (DZD)",
        "User",
      ],
    },

    Clients: {
      search_placeholder: "Name / Phone",
      nav_buttons: ["Client", "All"],
      clients_table_columns: ["Name", "Phone", "Debt"],
      modify_clients: [
        "Name",
        "Phone",
        "Debt",
        "All transactions",
        "Transactions last month",
        "Modify",
        "Add",
      ],
    },

    Settings: {
      components: ["Users", "Privileges", "Parameters"],

      Users: {
        components: [
          "Change Admins Password",
          "Add User",
          "Delte User",
          "Modify User",
        ],
        change_admin_password: ["Change password for the admin", "Save"],
        add_user: [
          "Create user",
          "Username",
          "Password",
          "Confirm Password",
          "Save",
        ],
        delete_user: [
          "Here's the list of your users",
          "Delete",
          "Users list is empty!",
        ],
        modify_user: [
          "Here's the list of your users",
          "Modify",
          "Users list is empty!",
          "Save",
          "New Username",
          "New Password",
        ],
      },

      Privileges: {
        fields: ["Select user", "Click to select"],
        sell: "Sell",
        add_products: "Add Products",
        grant_privileges: "Grant Privileges",
        import_products: "Import Products",
        access_clients: "Access Clients",
        delete_clients: "Delete Clients",
        credit_clients: "Credit Clients",
        access_settings: "Access Settings",
        delete_users: "Delete Users",
        access_parameters: "Access Parameters",
        access_transactions: "Access Transactions",
        access_inventory: "Access Inventory",
        delete_products: "Delete Products",
        modify_products: "Modify Products",
        print_inventory: "Print Inventory",
        add_clients: "Add Clients",
        modify_clients: "Modify Clients",
        print_clients_list: "Print Clients List",
        add_users: "Add Users",
        modify_users: "Modify Users",
        change_admin_password: "Change Admin Password",
      },

      Parameters: {
        header_text: "Change your parameters as you see fit",
        language_label: "Language",
        arabic: "Arabic",
        english: "English",
        french: "French",
        theme_label: "Theme",
        dark: "Dark Theme",
        green: "Green Theme",
        red: "Red Theme",
        blue: "Blue Theme",
      },
    },

    Info: {
      developper: "Developper",
      software: "Software",
      version: "Version",
      email: "Email",
      header: "Have any question? contact us",
      placeholders: ["Name", "Phone", "Email", "Write a message...", "Send"],
    },

    notifications: {
      login_page: [
        "Fields can not be empty, try again.",
        "Validation Failed!",
        "Loading",
      ],
      access_denied: "Access denied",
      empty_fields: "Fields can not be empty, try again",
      message_sent: "Your message have been sent, we will get back to you soon",
      something_went_wrong: "Something went wrong try again later",
      not_connected: "You are not connected to the internet, try again later",
      name_phone_message_cannot_be_empty:
        "Name, Phone and the message fields cannot be empty",
      duplicate_clients:
        "The client you are trying to add already exists in the database",
      client_saved: "Client saved!",
      updated: "Updated!",
      product_saved: "Product saved!",
      duplicate_product:
        "A product with the same name or barcode already exists in the database!",
      user_saved: "User saved!",
      passwords_not_matching: "Passwords do not match",
      admin_pass_updated: "Password updated!",
      db_empty: "Database is empty!",
      deleted: "Deleted!",
      debted_product_removed: "Product removed!",
      product_import_success: "Products imported successfully!",
      stock_limit: "Reached stock limit!",
      cant_credit_client: "Cannot credit client!",
      client_first: "You need to provide a client first!",
      pdf_generated: "PDF document generated and saved to your desktop",
      nothing_to_print: "Product list is empty!",
    },
  },

  fr: {
    Login_page: {
      title: "Connecter",
      username_placeholder: "Nom d'utilisateur",
      password_placeholder: "Mot de passe",
      trial_text: "Version d'essai",
      button_text: "Connecter",
      version_text: "POSoft version (1.0.0)",
    },

    Navigation: [
      "Caisse",
      "Stock",
      "Transactions",
      "Clients",
      "Parametres",
      "Info",
      "Quiter",
    ],

    Cash: {
      products_list_columns: ["Nom", "Quantite", "Prix (DZD)"],
      product_search_placeholder: "Nom/Code Barre",
      digital_screen: {
        text_fields: [
          "Numero de transaction",
          "Produit",
          "Prix",
          "Code Barre",
          "Stock",
          "Total",
        ],
        moving_bottom_text: "Soyer les bienvenus",
      },
      controls: [
        "Qty +",
        "Qty -",
        "Annuler",
        "Manual",
        "Valider",
        "Crediter",
        "Imprime recu",
      ],
      add_manual: {
        name_placeholder: "Entrer produit",
        value_placeholder: "Entrer valueur (DZD)",
        button: "Ajouter",
      },
      credit: {
        client_name_placeholder: "Entrer client",
        button: "Ajouter",
      },

      calculator: {
        input_placeholder: "Entrer montant (DZD)",
        button: "Calculer",
      },
    },

    Inventory: {
      search_placeholder: "Nom / Code Barre",
      nav_buttons: ["Ajouter", "Tous", "En Alert", "Importer", "Exporter PDF"],
      products_table_columns: [
        "Nom",
        "Code Barre",
        "Prix (DZD)",
        "Prix d'achat (DZD)",
        "Stock",
        "Quantite d'alert",
        "Modifier",
      ],
    },

    Transactions: {
      nav_fields: [
        "De",
        "Clicker pour selectioner",
        "A",
        "Filter par utilisateur",
        "TOTAL",
        "PROFIT",
      ],
      transactions_table_columns: [
        "Transaction #",
        "Date",
        "Temps",
        "Total (DZD)",
        "Utilisateur",
      ],
    },

    Clients: {
      search_placeholder: "Nom / Numero",
      nav_buttons: ["Client", "Tous"],
      clients_table_columns: ["Nom", "Numero", "Credit"],
      modify_clients: [
        "Nom",
        "Numero",
        "Credit",
        "Toutes les transactions",
        "Transactions du dernier mois",
        "Modifier",
        "Ajouter",
      ],
    },

    Settings: {
      components: ["Utilisateurs", "Privileges", "Reglage"],

      Users: {
        components: [
          "Changer mot de passe Admin",
          "Ajouter Utilisateur",
          "Suprimmer Utilisateur",
          "Modifier Utilisateur",
        ],
        change_admin_password: [
          "Changer le mot de passe pour Administrateur",
          "Sauvegarder",
        ],
        add_user: [
          "Ajouter Utilisateur",
          "Utilisateur",
          "Mot de Passe",
          "Confirmer Mot de Passe",
          "Sauvegarder",
        ],
        delete_user: [
          "Liste des utilisatuers",
          "Suprimmer",
          "Votre liste d'utilisateurs est vide!",
        ],
        modify_user: [
          "Liste des utilisatuers",
          "Modifier",
          "Votre liste d'utilisateurs est vide!",
          "Sauvegarder",
          "Nouveau nom d'utilisateur",
          "Nouveau mot de passe",
        ],
      },

      Privileges: {
        fields: ["Selectioner utilisateur", "Clicker pour selectionner"],
        sell: "Vendre",
        add_products: "Ajouter Produits",
        grant_privileges: "Accorder Privileges",
        import_products: "Importer Produits",
        access_clients: "Acceder Clients",
        delete_clients: "Supprimer Clients",
        credit_clients: "Crediter Clients",
        access_settings: "Acceder Parametres",
        delete_users: "Suprimmer Utilisateurs",
        access_parameters: "Acceder Reglage",
        access_transactions: "Acceder Transactions",
        access_inventory: "Acceder Stock",
        delete_products: "Suprimmer Produits",
        modify_products: "Modifier Produits",
        print_inventory: "Imprimer le Stock",
        add_clients: "Ajouter Clients",
        modify_clients: "Modifier Clients",
        print_clients_list: "Imprimmer liste des clients",
        add_users: "Ajouter Utilisateurs",
        modify_users: "Modifier Utilisateurs",
        change_admin_password: "Changer le mot de Passe Administrateurs",
      },

      Parameters: {
        header_text: "Changer vos reglage",
        language_label: "Langue",
        arabic: "Arab",
        english: "Anglais",
        french: "Francais",
        theme_label: "Theme",
        dark: "Dark Theme",
        green: "Green Theme",
        red: "Red Theme",
        blue: "Blue Theme",
      },
    },

    Info: {
      developper: "Developpeur",
      software: "Software",
      version: "Version",
      email: "Email",
      header: "Vous avez des questions ? Contactez-nous",
      placeholders: [
        "Nom",
        "Telephone",
        "Email",
        "Votre message...",
        "Envoyer",
      ],
    },

    notifications: {
      login_page: [
        "Les champs ne peuvent pas être vides, réessayez",
        "Validation échouée!",
        "Chargement!",
      ],
      access_denied: "Accès refusé",
      empty_fields: "Les champs ne peuvent pas être vides, réessayez",
      message_sent: "Votre message a été envoyé, nous vous répondrons bientôt",
      something_went_wrong:
        "Quelque chose s'est mal passé, réessayez plus tard",
      not_connected: "Vous n'êtes pas connecté à Internet, réessayez plus tard",
      name_phone_message_cannot_be_empty:
        "Les champs Nom, Téléphone et Message ne peuvent pas être vides",
      duplicate_clients: "Client deja existant dans la base de donnees",
      client_saved: "Client ajouter!",
      updated: "Changement sauveguarder",
      product_saved: "Produit ajouter!",
      duplicate_product:
        "Nom ou Code Barre déja existant dans la base de données, Impossible d'ajouter ce produit",
      user_saved: "Utilisateur ajouter!",
      passwords_not_matching: "Les mots de passe ne correspondent pas",
      admin_pass_updated: "Nouveau mot de passe sauveguarder",
      db_empty: "Base de données vide",
      deleted: "Supprimmé!",
      debted_product_removed: "Le produit crediter est supprimmé",
      product_import_success: "Produits telechargés",
      stock_limit: "Stock épuisé",
      cant_credit_client: "Impossible de crediter ce client",
      client_first: "Vous devez d'abord fournir un client",
      pdf_generated: "Document PDF généré et enregistré sur votre bureau!",
      nothing_to_print: "La liste des produits est vide",
    },
  },

  ar: {
    Login_page: {
      title: "تسجيل الدخول",
      username_placeholder: "اسم المستخدم",
      password_placeholder: "كلمة المرور",
      trial_text: "هذا الإصدار تجريبي",
      button_text: "تسجيل الدخول",
      version_text: "POSoft إصدار (1.0.0)",
    },
    Navigation: [
      "الصرافة",
      "المخزون",
      "المعاملات",
      "العملاء",
      "الإعدادات",
      "معلومات",
      "خروج",
    ],
    Cash: {
      products_list_columns: ["الاسم", "الكمية", "السعر (DZD)"],
      product_search_placeholder: "الاسم / الباركود",
      digital_screen: {
        text_fields: [
          "رقم الصفقة",
          "المنتج",
          "السعر",
          "الباركود",
          "في المخزون",
          "الإجمالي",
        ],
        moving_bottom_text: "شكرًا لتسوقك معنا",
      },
      controls: [
        "كمية +",
        "كمية -",
        "إلغاء",
        "اضافة يدوية",
        "تأكيد",
        "اقراض",
        "طباعة التذكير",
      ],
      add_manual: {
        name_placeholder: "أدخل المنتج",
        value_placeholder: "أدخل القيمة (DZD)",
        button: "إضافة",
      },
      credit: {
        client_name_placeholder: "أدخل اسم العميل",
        button: "إضافة",
      },
      calculator: {
        input_placeholder: "أدخل المبلغ (DZD)",
        button: "حساب",
      },
    },
    Inventory: {
      search_placeholder: "الاسم / الباركود",
      nav_buttons: [
        "إضافة",
        "اظهار الكل",
        "اقترب من النفاذ",
        "تحميل",
        "قائمة المنتجات",
      ],
      products_table_columns: [
        "الاسم",
        "الباركود",
        "السعر (DZD)",
        "سعر الشراء (DZD)",
        "المخزون",
        "كمية التنبيه",
        "تعديل",
      ],
    },
    Transactions: {
      nav_fields: [
        "من",
        "انقر للاختيار",
        "إلى",
        "المستخدم",
        "الإجمالي",
        "الربح",
      ],
      transactions_table_columns: [
        "الصفقة #",
        "التاريخ",
        "الوقت",
        "الإجمالي (DZD)",
        "المستخدم",
      ],
    },
    Clients: {
      search_placeholder: "الاسم / الهاتف",
      nav_buttons: ["اضافة عميل", "اظهار الكل"],
      clients_table_columns: ["الاسم", "الهاتف", "الدين"],
      modify_clients: [
        "الاسم",
        "الهاتف",
        "الدين",
        "جميع المعاملات",
        "معاملات الشهر الماضي",
        "تعديل",
        "إضافة",
      ],
    },
    Settings: {
      components: ["المستخدمين", "الصلاحيات", "الإعدادات"],
      Users: {
        components: [
          "تغيير كلمة مرور المشرف",
          "إضافة مستخدم",
          "حذف مستخدم",
          "تعديل مستخدم",
        ],
        change_admin_password: ["تغيير كلمة مرور المشرف", "حفظ"],
        add_user: [
          "إضافة مستخدم",
          "اسم المستخدم",
          "كلمة المرور",
          "تأكيد كلمة المرور",
          "حفظ",
        ],
        delete_user: ["قائمة المستخدمين", "مسح", "قائمة المستخدمين فارغة"],
        modify_user: [
          "قائمة المستخدمين",
          "تعديل",
          "قائمة المستخدمين فارغة",
          "حفظ",
          "الاسم الجديد",
          "كلمة السر الجديدة",
        ],
      },
      Privileges: {
        fields: ["اختر مستخدم", "انقر للاختيار"],
        sell: "بيع",
        add_products: "إضافة منتجات",
        grant_privileges: "منح الامتيازات",
        import_products: "استيراد المنتجات",
        access_clients: "الوصول إلى العملاء",
        delete_clients: "حذف العملاء",
        credit_clients: "اقراض العملاء",
        access_settings: "الوصول إلى الإعدادات",
        delete_users: "حذف المستخدمين",
        access_parameters: "الوصول إلى التعديلات",
        access_transactions: "الوصول إلى المعاملات",
        access_inventory: "الوصول إلى المخزون",
        delete_products: "حذف المنتجات",
        modify_products: "تعديل المنتجات",
        print_inventory: "طباعة المخزون",
        add_clients: "إضافة عملاء",
        modify_clients: "تعديل العملاء",
        print_clients_list: "طباعة قائمة العملاء",
        add_users: "إضافة مستخدمين",
        modify_users: "تعديل مستخدمين",
        change_admin_password: "تغيير كلمة مرور المدير",
      },

      Parameters: {
        header_text: "قم بتغيير إعداداتك حسب ما تراه مناسبًا",
        language_label: "لغة",
        arabic: "عربي",
        english: "إنجليزي",
        french: "فرنسي",
        theme_label: "الثيمات",
        dark: "Dark Theme",
        green: "Green Theme",
        red: "Red Theme",
        blue: "Blue Theme",
      },
    },

    Info: {
      developper: "المطور",
      software: "برنامج",
      version: "إصدار",
      email: "البريد الإلكتروني",
      header: "لديك أسئلة ؟ تواصل معنا",
      placeholders: [
        "الإ سم",
        "الهاتف",
        "البريد الإلكتروني",
        "رسالتك...",
        "ارسل",
      ],
    },

    notifications: {
      login_page: [
        "لا يمكن ترك حقول فارغة، حاول مرة أخرى.",
        "فشل التحقق!",
        "جاري التحميل",
      ],
      access_denied: "صلاحيات غير كافية",
      empty_fields: "تاكد من ادخال البيانات اللازمة",
      message_sent: "تم الارسال بنجاح",
      something_went_wrong: "حدث خطأ ما، حاول مرة أخرى لاحقًا",
      not_connected: "أنت غير متصل بالإنترنت، حاول مرة أخرى لاحقًا",
      name_phone_message_cannot_be_empty:
        "لا يمكن أن تكون حقول الاسم والهاتف والرسالة فارغة",
      client_saved: "تمت إضافة العميل بنجاح",
      duplicate_clients: "العميل موجود بالفعل في قاعدة البيانات",
      client_saved: "تمت اضافة العميل بنجاح",
      updated: "تم حفظ التغييرات",
      product_saved: "تمت إضافة المنتج!",
      duplicate_product:
        "الاسم أو رمز الباركود موجود بالفعل في قاعدة البيانات، لا يمكن إضافة هذا المنتج",
      user_saved: "تمت إضافة المستخدم",
      passwords_not_matching: "كلمات المرور غير متطابقة",
      admin_pass_updated: "تم حفظ كلمة المرور الجديدة",
      db_empty: "قاعدة البيانات فارغة",
      deleted: "تم الحذف",
      debted_product_removed: "تم حذف المنتج",
      product_import_success: "تم تحميل المنتجات",
      stock_limit: "المخزون نفد",
      cant_credit_client: "لا يمكن إضافة رصيد لهذا العميل",
      client_first: "يجب تحديد العميل أولاً",
      pdf_generated: "تم إنشاء الملف وحفظه على سطح المكتب الخاص بك",
      nothing_to_print: "القائمة فارغة",
    },
  },
};

export default Langs;
